USE PIZZARIAS_FS

--INSERT INTO CREDENCIAIS(CREDENCIAL) VALUES ('administrador'), ('usuario');
SELECT * FROM CREDENCIAIS

--INSERT INTO USUARIOS(EMAIL, SENHA, ID_CREDENCIAL) VALUES ('gandolf', '132', 1), ('gabriel@mail.com', '123', 2);
SELECT * FROM USUARIOS

--INSERT INTO CATEGORIAS(CATEGORIA) VALUES ('menos de 30'), ('31 a 50'), ('mais de 50');
SELECT * FROM CATEGORIAS

-- INSERT INTO PIZZARIAS(NOME, ENDERECO, NUMERO, TELEFONE, VEGANA, ID_CATEGORIA)
-- VALUES ('A Viagem', 'Av Rubens Fraga de Toledo Arruda', 456, 1125251919, 1, 3)
SELECT * FROM PIZZARIAS