--REATE DATABASE PIZZARIAS_FS

USE PIZZARIAS_FS

CREATE TABLE CREDENCIAIS (
    ID INT IDENTITY PRIMARY KEY,
    CREDENCIAL VARCHAR(100) NOT NULL,
)

CREATE TABLE USUARIOS (
    ID INT IDENTITY PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL,
    ID_CREDENCIAL INT FOREIGN KEY REFERENCES CREDENCIAIS(ID) DEFAULT 2
)

CREATE TABLE CATEGORIAS (
    ID INT IDENTITY PRIMARY KEY,
    CATEGORIA VARCHAR(100) NOT NULL,
)

CREATE TABLE PIZZARIAS (
    ID INT IDENTITY PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    ENDERECO VARCHAR(200) NOT NULL,
    NUMERO INT NOT NULL,
    TELEFONE VARCHAR(200) NOT NULL,
    VEGANA BIT NOT NULL DEFAULT 0,
    ID_CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIAS(ID)
)